tao:
  image: alroniks/tao:latest
  links:
    - db
web:
  image: nginx:latest
  ports:
    - "80:80"
  volumes_from:
    - tao
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - tao
db:
  image: mysql:8
  command: --default-authentication-plugin=mysql_native_password
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: r00t
    MYSQL_USER: tao
    MYSQL_PASSWORD: tao
    MYSQL_DATABASE: tao
    
